In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv("supplement.csv")
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [5]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [6]:
dataset.describe()

Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [8]:
import plotly.express as px

In [17]:
pie1 = dataset["Store_Type"].value_counts()
store = pie1.index
orders = pie1.values
fig = px.pie(dataset, values = orders, names = store)
fig.show()

In [18]:
pie2 = dataset["Location_Type"].value_counts()
loc = pie2.index
orders1 = pie2.values
fig = px.pie(dataset, values = orders1, names = loc)
fig.show()

In [19]:
pie3 = dataset["Discount"].value_counts()
dis = pie3.index
orders2 = pie3.values
fig = px.pie(dataset, values = orders2, names = dis)
fig.show()

In [20]:
pie4 = dataset["Holiday"].value_counts()
holiday = pie4.index
orders3 = pie4.values
fig = px.pie(dataset, values = orders3, names = holiday)
fig.show()

In [21]:
dataset["Discount"] = dataset["Discount"].map({"No":0, "Yes":1})

In [22]:
dataset["Store_Type"] = dataset["Store_Type"].map({"S1":1, "S2":2, "S3":3, "S4":4})

In [23]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1":1, "L2":2, "L3":3, "L4":4, "L5":5})

In [25]:
X = np.array(dataset[["Store_Type", "Location_Type", "Holiday", "Discount"]])
y = np.array(dataset["#Order"])

In [26]:
X

array([[1, 3, 1, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 1],
       ...,
       [1, 3, 1, 0],
       [3, 1, 1, 1],
       [2, 1, 1, 0]], dtype=int64)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

In [31]:
pip install lightgbm

     ---------------------------------------- 1.0/1.0 MB 1.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [32]:
import lightgbm as ltb

In [33]:
model = ltb.LGBMRegressor()
model.fit(X_train, y_train)

LGBMRegressor()

In [34]:
y_pred = model.predict(X_test)

In [37]:
y_test

array([125, 119,  84, ...,  54,  52,  49], dtype=int64)

In [36]:
y_pred

array([ 85.49400645, 103.68098632,  72.98578728, ...,  54.44463049,
        47.41063831,  84.91048168])

In [35]:
data_pred = pd.DataFrame(data = {"Predicted orders": y_pred.flatten()})
data_pred

Predicted orders
0             85.494006
1            103.680986
2             72.985787
3             85.494006
4             33.628361
...                 ...
37663         50.818619
37664         41.214447
37665         54.444630
37666         47.410638
37667         84.910482

[37668 rows x 1 columns]